Repository prgrms-web-devcourse-final-project/WEB5_6_SamSamOO_FE, pull requests merged in 2025-09, with the labels that each got.

#51 style : 회원가입, 계정찾기, 비밀번호 재설정 ui 제작
  package-lock.json
  package.json
  public/icons/selectDown.svg
  public/icons/selectUp.svg
  src/app/(account)/find-account/page.tsx
  src/app/(account)/layout.tsx
  src/app/(account)/login/layout.tsx
  src/app/(account)/login/page.tsx
  src/app/(account)/password-reset/page.tsx
  src/app/(account)/sign-up/page.tsx
  src/components/features/account/AccountButton.tsx
  src/components/features/account/AccountInput.tsx
  src/components/features/account/BirthdayInput.tsx
  src/components/features/account/SelectGender.tsx
  src/components/ui/AccountButton.tsx
Labels: style

#57 Feat & Style & Chore : 검색 페이지 기능 및 UI 작업, 공통 컴포넌트 추가
  public/icons/filter.png
  public/icons/filterDown.svg
  public/icons/floatingChat.svg
  public/icons/floatingUpButton.svg
  public/icons/search.svg
  public/icons/select.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/(search-layout)/law/[id]/page.tsx
  src/app/search/(search-layout)/law/page.tsx
  src/app/search/(search-layout)/layout.tsx
  src/app/search/(search-layout)/precedent/[id]/page.tsx
  src/app/search/(search-layout)/precedent/page.tsx
  src/app/search/(search-layout)/total/page.tsx
  src/app/search/page.tsx
  src/app/test/page.tsx
  src/components/features/account/AccountInput.tsx
  src/components/features/search/AppliedFilter.tsx
  src/components/features/search/LawSearchFilterModal.tsx
  src/components/features/search/PrecedentSearchFilterModal.tsx
  src/components/features/search/SearchFilter.tsx
  src/components/features/search/SearchForm.tsx
  src/components/features/search/SearchInput.tsx
  src/components/features/search/TotalSearchFilterModal.tsx
  src/components/features/search/_testData/mockData.ts
  src/components/features/search/_testData/mockDataLaw.json
  src/components/features/search/_testData/mockDataLawDetail.json
  src/components/features/search/_testData/mockDataPrecdentDetail.json
  src/components/features/search/_testData/mockDataPrecedent.json
  src/components/features/search/_testData/test.txt
  src/components/features/search/navigationItems.ts
  src/components/layout/Header.tsx
  src/components/layout/ToggleThemeButton.tsx
  src/components/ui/ScrollButton.tsx
  src/components/ui/SelectMenu.tsx
  src/components/ui/ToggleSwitchNavigation.tsx
  src/hooks/useClosePopup.ts
  src/styles/_base.css
  src/styles/_theme.css
  src/types/global.ts
  src/types/navigationItems.ts
  src/utils/convertObjectToString.ts
Labels: feat, style, chore

#60 chore: 넥스트 SVGR,SVGO 변환 설정
  next.config.ts
  package-lock.json
  package.json
Labels: chore
